LIBWHCA-275. Preserve "content_after_closing_html" behavior
After updating the dependencies the following test failed when running pytest:

```
================================================================================ FAILURES ================================================================================
_ test_content_after_closing_html[<html><body><p><br></p></body></html><img src="https://www.example.com/cat_photo" height="49">-<html><body><p><br/></p><div><html><body><img height="49" src="https://www.example.com/cat_photo"/></body></html></div></body></html>] _

value = '<html><body><p><br></p></body></html><img src="https://www.example.com/cat_photo" height="49">'
expected = '<html><body><p><br/></p><div><html><body><img height="49" src="https://www.example.com/cat_photo"/></body></html></div></body></html>'

    @pytest.mark.parametrize(
        ('value', 'expected'),
        [
            ('<html><body><p><br></p></body></html><img src="https://www.example.com/cat_photo" height="49">',
             '<html><body><p><br/></p><div><html><body><img height="49" src="https://www.example.com/cat_photo"/></body></html></div></body></html>'),
             ('<html><body><p><br></p></body></html>',
             '<html><body><p><br></p></body></html>'),
             ('<p><br></p>',
             '<p><br></p>'),
        ]
    )
    def test_content_after_closing_html(value, expected):
        result = str(content_after_closing_html(value))
>       assert result == expected
E       assert '<html><body>...oto"/></html>' == '<html><body>.../body></html>'
E
E         Skipping 122 identical leading characters in diff, use -v to show
E         - ody></html>
E         + ody></html><html><img height="49" src="https://www.example.com/cat_photo"/></html>

tests/test_clean.py:21: AssertionError
======================================================================== short test summary info =========================================================================
FAILED tests/test_clean.py::test_content_after_closing_html[<html><body><p><br></p></body></html><img src="https://www.example.com/cat_photo" height="49">-<html><body><p><br/></p><div><html><body><img height="49" src="https://www.example.com/cat_photo"/></body></html></div></body></html>] - assert '<html><body>...oto"/></html>' == '<html><body>.../body></html>'
====================================================================== 1 failed, 27 passed in 0.18s ======================================================================
```

This test failure is caused by the update of the lxml dependency for
v5.1.0 to 6.1.1.

In the test, HTML with an image tag after the closing `</html>` tag is
provided:

```
<html><body><p><br></p></body></html><img src="https://www.example.com/cat_photo" height="49">
```

Prior to the upgrade (in the “content_after_closing_html” method in
“src/processing/common/clean.py”), BeautifulSoup would truncate this to:

```
<html><body><p><br></p></body></html>
```

After the upgrade, BeautifulSoup no longer does this, and retains the
full HTML:

```
<html><body><p><br></p></body></html><img src="https://www.example.com/cat_photo" height="49">
```

which was causing the test to fail.

This test was added as part of LIBWHCA-124, and it was not clear if the
new behavior was better than the old behavior. It was decided to
attempt to preserve the old behavior, so instead of updating the
expected result for the test, instead modified the
“content_after_closing_html” method in “src/processing/common/clean.py”
to mimic the old behavior by stripping the post-</html> content from the
string based to BeautifulSoup, and then proceeding with the rest of the
method.

This enabled the test to pass without change to the given or expected
values.

https://umd-dit.atlassian.net/browse/LIBWHCA-275