LIBWHCA-275. Update Django to latest 5.1.x version
Updated Django to 5.1.15, which it the latest 5.0.x version as of
July 6, 2026.

Also updated the "asgiref" package to the latest v3.11.1 version due
to a dependency conflict when running `pip install -e '.[test]'`:

```
ERROR: Cannot install None and scutes because these package versions have conflicting dependencies.

The conflict is caused by:
    scutes 2.0.0.dev0 depends on asgiref==3.7.2
    django 5.1.15 depends on asgiref<4 and >=3.8.1
```

https://umd-dit.atlassian.net/browse/LIBWHCA-275